cfe_sbn_bridge:
  ros__parameters:
    plugin_name: cfe_sbn_plugin.cfe_sbn_plugin
    namespace: /flightsystem
    plugin_params:
      msg_pkg: cfe_msgs
      udp_receive_port: 2236
      udp_receive_ip: '0.0.0.0'
      spacecraft_id: 66
      processor_id: 3
      epoch_delta: 315532800
      rosout_name_max_length: 32
      rosout_msg_max_length: 128
      rosout_file_max_length: 64
      rosout_function_max_length: 32
      # fsw information
      peer_ip: "10.5.0.3"         # IP for fsw (if same machine, use 127.0.0.1) 
      peer_port: 2235             # 2234 for cpu1, 2235 for cpu2
      peer_processor_id: 2        # Processor id (1 or 2, for cpu1 - singlehost setup, or cpu2 - multihost setup)

